/**
 * 프로젝트 전체 한국어 문구 상수
 * 절대 수정 금지 - 1글자도 변경하지 말 것
 */

export const STRINGS = {
  // 공통
  COMMON: {
    HOME: '홈',
    BACK: '뒤로가기',
    CLOSE: '닫기',
    SAVE: '저장',
    CANCEL: '취소',
    ADD: '추가',
    DELETE: '삭제',
    EDIT: '수정',
    SEARCH: '검색',
    LOADING: '로딩 중...',
    NO_DATA: '데이터가 없습니다',
    ERROR: '오류가 발생했습니다',
    SUCCESS: '성공',
    CONFIRM: '확인',
    IMAGE_LOADING: '이미지 준비중',
  },

  // 로그인/회원가입
  AUTH: {
    LOGIN_TITLE: '로그인',
    SIGNUP_TITLE: '회원가입',
    WELCOME_MESSAGE: '치팡 주문 시스템에 오신 것을 환영합니다',
    BUSINESS_NO: '사업자번호',
    BUSINESS_NO_PLACEHOLDER: '000-00-00000',
    PASSWORD: '비밀번호',
    PASSWORD_PLACEHOLDER: '비밀번호를 입력하세요',
    PASSWORD_CONFIRM: '비밀번호 확인',
    PASSWORD_CONFIRM_PLACEHOLDER: '비밀번호를 다시 입력하세요',
    ACCOUNT_TYPE: '계정 유형',
    DENTAL: '치과',
    ADMIN: '관리자',
    LOGIN_BUTTON: '로그인',
    SIGNUP_BUTTON: '회원가입',
    LOGGING_IN: '로그인 중...',
    SIGNING_UP: '가입 중...',
    GO_TO_SIGNUP: '회원가입',
    GO_TO_LOGIN: '로그인',
    TEST_ACCOUNT: '테스트 계정',
    CLINIC_NAME: '치과명',
    CLINIC_NAME_PLACEHOLDER: '예: 서울치과의원',
    CONTACT_NAME: '담당자명',
    CONTACT_NAME_PLACEHOLDER: '홍길동',
    PHONE: '휴대폰',
    PHONE_PLACEHOLDER: '010-0000-0000',
    OPTIONAL: '(선택)',
    ERROR_BUSINESS_NO_NOT_FOUND: '등록되지 않은 사업자번호입니다.',
    ERROR_WRONG_PASSWORD: '비밀번호가 올바르지 않습니다.',
    ERROR_LOGIN_FAILED: '로그인 중 오류가 발생했습니다.',
    ERROR_PASSWORD_MISMATCH: '비밀번호가 일치하지 않습니다.',
    ERROR_BUSINESS_NO_EXISTS: '이미 등록된 사업자번호입니다.',
    ERROR_SIGNUP_FAILED: '회원가입 중 오류가 발생했습니다.',
    SUCCESS_SIGNUP: '회원가입이 완료되었습니다.',
    ADMIN_TEST_ACCOUNT: '관리자: 761-88-01913',
    DENTAL_TEST_ACCOUNT: '치과: 123-45-67890',
  },

  // 제품 관리
  PRODUCT_MANAGEMENT: {
    TITLE: '제품 관리',
    SUBTITLE: '이미지 URL·단가는 셀을 클릭해 바로 수정할 수 있습니다',
    ADD_PRODUCT: '제품 추가',
    EXPORT_CSV: 'CSV 내보내기',
    TOTAL_PRODUCTS: '전체 제품',
    ACTIVE_PRODUCTS: '활성 제품',
    INACTIVE_PRODUCTS: '비활성 제품',
    SEARCH_PLACEHOLDER: '제품명, 모델명으로 검색...',
    ALL_CATEGORIES: '전체 카테고리',
    ALL_STATUS: '전체 상태',
    ACTIVE: '활성',
    INACTIVE: '비활성',
    QUICK_EDIT_HINT: '이미지 URL 또는 단가 셀을 클릭하면 바로 수정할 수 있습니다. Enter로 저장, Esc로 취소.',
    IMAGE_URL: '이미지 URL',
    UNIT_PRICE: '단가 (원)',
    CLICK_TO_EDIT: '(클릭 수정)',
    STATUS: '상태',
    ACTIONS: '작업',
    VIEW_DETAIL: '상세 보기',
    EDIT_ALL: '전체 수정',
    NO_PRODUCTS: '제품이 없습니다',
    SAVED: '저장되었습니다.',
    CSV_DOWNLOADED: 'CSV 파일이 다운로드되었습니다.',
  },

  // 제품 상세
  PRODUCT_DETAIL: {
    BREADCRUMB_HOME: '홈',
    IN_STOCK: '재고 있음',
    MAIN_FEATURES: '주요 특징',
    SELECT_OPTIONS: '옵션 선택',
    QUANTITY: '수량',
    ADD_TO_CART: '장바구니 담기',
    ADDED_TO_CART: '장바구니 담김!',
    REQUEST_QUOTE: '견적 요청',
    QUICK_SPECS: '빠른 사양',
    TECH_SPECS: '기술 사양',
    FEATURES: '주요 특징',
    SPEC_IMAGES: '규격표 이미지',
    DRILL_SEQUENCE: '드릴 시퀀스',
    NO_SPECS: '사양 정보가 없습니다.',
    NO_FEATURES: '특징 정보가 없습니다.',
    SPEC_IMAGE_PREVIEW: '규격표 이미지 미리보기',
    VIEW_ALL: '전체 보기',
    CLICK_TO_ENLARGE: '이미지를 클릭하면 크게 볼 수 있습니다.',
    PREVIOUS: '이전',
    NEXT: '다음',
    ENLARGE: '확대 보기',
  },

  // 견적 요청
  QUOTE_REQUEST: {
    TITLE: '견적 / 주문 요청',
    SUBMITTED_TITLE: '요청이 접수되었습니다',
    SUBMITTED_MESSAGE: '담당자가 확인 후 빠르게 연락드리겠습니다.',
    PRODUCT: '제품',
    MODEL_CODE: '모델코드',
    OPTIONS: '옵션',
    QUANTITY: '수량',
    CLINIC_NAME: '치과명 / 기관명',
    CLINIC_NAME_PLACEHOLDER: '예) 서울치과의원',
    CONTACT_NAME: '담당자명',
    CONTACT_NAME_PLACEHOLDER: '홍길동',
    PHONE: '연락처',
    PHONE_PLACEHOLDER: '010-0000-0000',
    EMAIL: '이메일',
    EMAIL_PLACEHOLDER: 'example@email.com',
    MESSAGE: '추가 요청사항',
    MESSAGE_PLACEHOLDER: '추가 옵션, 납기 요청, 기타 문의사항을 입력해주세요.',
    SUBMIT: '견적 요청 보내기',
    SUBMITTING: '전송 중...',
    REQUIRED: '*',
  },

  // 키트 구성품
  KIT_COMPONENTS: {
    TITLE: '구성품 상세',
    SUBTITLE: '에 포함된 모든 구성품을 확인하세요.',
    SIMPLE_KIT: 'Simple Kit',
    FULL_KIT: 'Full Kit',
    PREMIUM: '프리미엄',
    KIT_PRICE: '키트 가격',
    SIMPLE_KIT_PRICE: 'Simple Kit 가격',
    FULL_KIT_PRICE: 'Full Kit 가격',
    COMPONENTS_COUNT: '종 구성',
    NO: 'No.',
    IMAGE: '이미지',
    COMPONENT_NAME: '구성품명',
    CODE: '코드',
    QUANTITY_DESC: '수량',
    NOTE: '비고',
    TOTAL_COMPONENTS: '총',
    COMPONENTS_INCLUDED: '구성품 포함',
    SIMPLE_INCLUDED: 'Simple 포함',
    FULL_ONLY: 'Full 전용',
    STERILIZATION_TITLE: '멸균 및 관리 안내',
    STERILIZATION_1: '오토클레이브 멸균: 134°C, 3bar, 18분 권장',
    STERILIZATION_2: '사용 전 초음파 세척 후 멸균 진행',
    STERILIZATION_3: '전용 케이스에 보관하여 기구 손상 방지',
  },

  // 드릴 시퀀스
  DRILL_SEQUENCE: {
    TITLE: '수술 순서 가이드',
    SUBTITLE: '모델의 권장 드릴 시퀀스입니다',
    WARNING_TITLE: '수술 전 확인사항',
    WARNING_1: '골질(D1-D4)에 따라 드릴 시퀀스를 조정하세요',
    WARNING_2: '충분한 생리식염수 냉각을 유지하세요',
    WARNING_3: '드릴 회전 속도와 압력을 준수하세요',
    DIAMETER: '직경',
    DEPTH: '깊이',
    SPEED: '속도',
    INFO_TITLE: '추가 안내',
    INFO_1: '골질이 단단한 경우(D1-D2) 탭핑을 권장합니다',
    INFO_2: '골질이 무른 경우(D3-D4) 탭핑을 생략할 수 있습니다',
    INFO_3: '최종 식립 시 35Ncm 이상의 초기 고정력을 확보하세요',
  },

  // 카테고리 제품 카드
  CATEGORY_CARD: {
    VIEW_DETAIL: '상세보기',
    ORDER: '주문하기',
    PREPARING: '준비중',
  },

  // 주문 제품 카드
  ORDER_CARD: {
    KIT: 'KIT',
    SIMPLE: 'Simple',
    FULL: 'Full',
    PER_ITEM: '/ 개',
    ADD_COMPONENTS: '구성품',
    AVAILABLE_COMPONENTS: '함께 구성 가능한 제품',
    COMPONENTS_SELECTED: '종 선택됨',
    QUANTITY: '수량',
    CART: '장바구니',
    ADDED: '담김!',
    SET: '세트',
    DETAIL: '상세',
    INQUIRY: '문의',
    INQUIRY_TITLE: '제품 문의',
    INQUIRY_SUBMITTED: '문의가 접수되었습니다',
    INQUIRY_SUBMITTED_MESSAGE: '빠른 시일 내에 연락드리겠습니다.',
    NAME: '이름',
    PHONE: '연락처',
    EMAIL: '이메일',
    CLINIC_NAME: '치과명',
    INTERESTED_PRODUCT: '관심 제품',
    MESSAGE: '문의 내용',
    MESSAGE_PLACEHOLDER: '문의하실 내용을 입력해주세요 (최대 500자)',
    SUBMIT: '문의하기',
    SUBMITTING: '전송 중...',
    REQUIRED: '*',
  },

  // 제품 모달
  PRODUCT_MODAL: {
    EDIT_TITLE: '제품 정보 수정',
    ADD_TITLE: '새 제품 추가',
    BASIC_INFO: '기본 정보',
    NAME_KO: '제품명 (한글)',
    NAME_EN: '제품명 (영문)',
    MODEL_CODE: '모델코드',
    MODEL_CODE_PLACEHOLDER: '예: HN-BA',
    CATEGORY: '카테고리',
    SHORT_DESC: '간단 설명',
    SHORT_DESC_PLACEHOLDER: '제품에 대한 간단한 설명을 입력하세요',
    BASE_PRICE: '기본 단가 (원)',
    STATUS: '상태',
    ACTIVE: '활성',
    INACTIVE: '비활성',
    IMAGE: '이미지',
    IMAGE_URL: '이미지 URL',
    IMAGE_URL_PLACEHOLDER: 'https:// 또는 /assets/...',
    IMAGE_FILE_UPLOAD: '또는 이미지 파일 업로드',
    FILE_SELECT: '파일 선택',
    UPLOADING: '업로드 중...',
    FILE_SIZE_LIMIT: 'JPG, PNG, GIF (최대 5MB)',
    IMAGE_FIT: '이미지 맞춤',
    FIT_CONTAIN: '전체 보이기 (Contain)',
    FIT_COVER: '꽉 채우기 (Cover)',
    PREVIEW: '미리보기',
    SPEC_IMAGES: '규격표 이미지',
    ADD_SPEC_IMAGE: '규격표 추가',
    NO_SPEC_IMAGES: '규격표 이미지가 없습니다',
    SPEC_IMAGE_NUM: '규격표',
    SPEC_IMAGE_PLACEHOLDER: '이미지 URL 입력',
    FILE_UPLOAD: '파일 업로드',
    OPTIONS: '제품 옵션',
    ADD_OPTION: '옵션 추가',
    OPTION_LABEL_PLACEHOLDER: '옵션명 (예: 직경)',
    OPTION_VALUES_PLACEHOLDER: '옵션값 (쉼표로 구분, 예: 3.5mm, 4.0mm)',
    SPECS: '기술 사양',
    ADD_SPEC: '사양 추가',
    NO_SPECS: '기술 사양이 없습니다',
    SPEC_LABEL_PLACEHOLDER: '항목 (예: 소재)',
    SPEC_VALUE_PLACEHOLDER: '값 (예: Grade 5 티타늄)',
    FEATURES: '주요 특징',
    ADD_FEATURE: '특징 추가',
    FEATURE_PLACEHOLDER: '특징 설명 (예: 높은 정밀도와 내구성)',
    CANCEL: '취소',
    SAVE: '저장',
    ADD: '추가',
    IMAGE_UPLOADED: '이미지가 업로드되었습니다.',
    IMAGE_UPLOAD_FAILED: '이미지 업로드에 실패했습니다.',
    IMAGE_SIZE_ERROR: '이미지 파일은 5MB 이하만 업로드 가능합니다.',
    IMAGE_TYPE_ERROR: '이미지 파일만 업로드 가능합니다.',
    SPEC_IMAGE_UPLOADED: '규격표 이미지가 업로드되었습니다.',
    PRODUCT_UPDATED: '제품 정보가 수정되었습니다.',
    PRODUCT_ADDED: '새 제품이 추가되었습니다.',
  },
} as const;